#!/bin/bash
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

# You can use CC CFALGS LD LDFLAGS CXX CXXFLAGS AR RANLIB READELF STRIP here
${CC} ${CFLAGS} minimalPkg.c -o minimalPkg

make ${MAKE_FLAGS}
